# Generated by Django 4.2.2 on 2023-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semisters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourthtwo',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('htno', models.TextField(blank=True, db_column='Htno', null=True)),
                ('subcode', models.TextField(blank=True, db_column='Subcode', null=True)),
                ('subname', models.TextField(blank=True, db_column='Subname', null=True)),
                ('grade', models.TextField(blank=True, db_column='Grade', null=True)),
                ('credits', models.IntegerField(blank=True, db_column='Credits', null=True)),
            ],
            options={
                'db_table': 'fourthtwo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Fourtwo',
        ),
    ]
